SELECT 'Upgrading MetaStore schema from 3.0.0 to 3.1.0' AS MESSAGE;

-- HIVE-19440: add AUTHORIZER column and rebuild privilege indexes idempotently.
-- Hopsworks deployments may already have AUTHORIZER in some tables (partial prior run),
-- so every operation is guarded by an INFORMATION_SCHEMA check.
--
-- IMPORTANT: PREPARE/EXECUTE/DEALLOCATE PREPARE must each be on their own line.
-- HiveSchemaTool sets beeline's setEntireLineAsCommand(true), and the buildCommand
-- parser accumulates lines until a line ending with ";" then flushes the whole buffer
-- as ONE beeline statement. Multiple statements on one line → MySQL syntax error 1064.
--
-- FK NOTE: For tables whose privilege index is used as the FK backing index
-- (DB_PRIVS, TBL_PRIVS, PART_PRIVS, TBL_COL_PRIVS, PART_COL_PRIVS), MySQL/NDB
-- refuses to drop the index while the FK exists (error 1553). The fix is:
-- drop FK first, drop old index, add new index with AUTHORIZER first, re-add FK.

-- ---- GLOBAL_PRIVS (no FK) ----
SET @_col = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
             WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='GLOBAL_PRIVS' AND COLUMN_NAME='AUTHORIZER');
SET @_sql = IF(@_col=0, 'ALTER TABLE `GLOBAL_PRIVS` ADD `AUTHORIZER` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL', 'SELECT 1');
PREPARE _s FROM @_sql;
EXECUTE _s;
DEALLOCATE PREPARE _s;

SET @_need = (SELECT IF(COUNT(*)=0,1,0) FROM INFORMATION_SCHEMA.STATISTICS
              WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='GLOBAL_PRIVS'
                AND INDEX_NAME='GLOBALPRIVILEGEINDEX' AND COLUMN_NAME='AUTHORIZER' AND SEQ_IN_INDEX=1);
SET @_sql = IF(@_need=1 AND (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='GLOBAL_PRIVS' AND INDEX_NAME='GLOBALPRIVILEGEINDEX')>0, 'ALTER TABLE `GLOBAL_PRIVS` DROP INDEX `GLOBALPRIVILEGEINDEX`', 'SELECT 1');
PREPARE _s FROM @_sql;
EXECUTE _s;
DEALLOCATE PREPARE _s;
SET @_sql = IF(@_need=1, 'ALTER TABLE `GLOBAL_PRIVS` ADD CONSTRAINT `GLOBALPRIVILEGEINDEX` UNIQUE(`AUTHORIZER`,`PRINCIPAL_NAME`,`PRINCIPAL_TYPE`,`USER_PRIV`,`GRANTOR`,`GRANTOR_TYPE`)', 'SELECT 1');
PREPARE _s FROM @_sql;
EXECUTE _s;
DEALLOCATE PREPARE _s;

-- ---- DB_PRIVS (FK: DB_PRIVS_FK1 on DB_ID → DBS.DB_ID) ----
SET @_col = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
             WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='DB_PRIVS' AND COLUMN_NAME='AUTHORIZER');
SET @_sql = IF(@_col=0, 'ALTER TABLE `DB_PRIVS` ADD `AUTHORIZER` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL', 'SELECT 1');
PREPARE _s FROM @_sql;
EXECUTE _s;
DEALLOCATE PREPARE _s;

SET @_need = (SELECT IF(COUNT(*)=0,1,0) FROM INFORMATION_SCHEMA.STATISTICS
              WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='DB_PRIVS'
                AND INDEX_NAME='DBPRIVILEGEINDEX' AND COLUMN_NAME='AUTHORIZER' AND SEQ_IN_INDEX=1);
SET @_fk_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE() AND TABLE_NAME='DB_PRIVS' AND CONSTRAINT_NAME='DB_PRIVS_FK1' AND CONSTRAINT_TYPE='FOREIGN KEY');
SET @_sql = IF(@_need=1 AND @_fk_exists=1, 'ALTER TABLE `DB_PRIVS` DROP FOREIGN KEY `DB_PRIVS_FK1`', 'SELECT 1');
PREPARE _s FROM @_sql;
EXECUTE _s;
DEALLOCATE PREPARE _s;
SET @_sql = IF(@_need=1 AND (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='DB_PRIVS' AND INDEX_NAME='DBPRIVILEGEINDEX')>0, 'ALTER TABLE `DB_PRIVS` DROP INDEX `DBPRIVILEGEINDEX`', 'SELECT 1');
PREPARE _s FROM @_sql;
EXECUTE _s;
DEALLOCATE PREPARE _s;
SET @_sql = IF(@_need=1, 'ALTER TABLE `DB_PRIVS` ADD CONSTRAINT `DBPRIVILEGEINDEX` UNIQUE(`AUTHORIZER`,`DB_ID`,`PRINCIPAL_NAME`,`PRINCIPAL_TYPE`,`DB_PRIV`,`GRANTOR`,`GRANTOR_TYPE`)', 'SELECT 1');
PREPARE _s FROM @_sql;
EXECUTE _s;
DEALLOCATE PREPARE _s;
SET @_fk_now = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE() AND TABLE_NAME='DB_PRIVS' AND CONSTRAINT_NAME='DB_PRIVS_FK1' AND CONSTRAINT_TYPE='FOREIGN KEY');
SET @_sql = IF(@_need=1 AND @_fk_now=0, 'ALTER TABLE `DB_PRIVS` ADD CONSTRAINT `DB_PRIVS_FK1` FOREIGN KEY (`DB_ID`) REFERENCES `DBS` (`DB_ID`)', 'SELECT 1');
PREPARE _s FROM @_sql;
EXECUTE _s;
DEALLOCATE PREPARE _s;

-- ---- TBL_PRIVS (FK: TBL_PRIVS_FK1 on TBL_ID → TBLS.TBL_ID) ----
SET @_col = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
             WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='TBL_PRIVS' AND COLUMN_NAME='AUTHORIZER');
SET @_sql = IF(@_col=0, 'ALTER TABLE `TBL_PRIVS` ADD `AUTHORIZER` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL', 'SELECT 1');
PREPARE _s FROM @_sql;
EXECUTE _s;
DEALLOCATE PREPARE _s;

SET @_need = (SELECT IF(COUNT(*)=0,1,0) FROM INFORMATION_SCHEMA.STATISTICS
              WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='TBL_PRIVS'
                AND INDEX_NAME='TABLEPRIVILEGEINDEX' AND COLUMN_NAME='AUTHORIZER' AND SEQ_IN_INDEX=1);
SET @_fk_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE() AND TABLE_NAME='TBL_PRIVS' AND CONSTRAINT_NAME='TBL_PRIVS_FK1' AND CONSTRAINT_TYPE='FOREIGN KEY');
SET @_sql = IF(@_need=1 AND @_fk_exists=1, 'ALTER TABLE `TBL_PRIVS` DROP FOREIGN KEY `TBL_PRIVS_FK1`', 'SELECT 1');
PREPARE _s FROM @_sql;
EXECUTE _s;
DEALLOCATE PREPARE _s;
SET @_sql = IF(@_need=1 AND (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='TBL_PRIVS' AND INDEX_NAME='TABLEPRIVILEGEINDEX')>0, 'ALTER TABLE `TBL_PRIVS` DROP INDEX `TABLEPRIVILEGEINDEX`', 'SELECT 1');
PREPARE _s FROM @_sql;
EXECUTE _s;
DEALLOCATE PREPARE _s;
SET @_sql = IF(@_need=1, 'ALTER TABLE `TBL_PRIVS` ADD INDEX `TABLEPRIVILEGEINDEX`(`AUTHORIZER`,`TBL_ID`,`PRINCIPAL_NAME`,`PRINCIPAL_TYPE`,`TBL_PRIV`,`GRANTOR`,`GRANTOR_TYPE`)', 'SELECT 1');
PREPARE _s FROM @_sql;
EXECUTE _s;
DEALLOCATE PREPARE _s;
SET @_fk_now = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE() AND TABLE_NAME='TBL_PRIVS' AND CONSTRAINT_NAME='TBL_PRIVS_FK1' AND CONSTRAINT_TYPE='FOREIGN KEY');
SET @_sql = IF(@_need=1 AND @_fk_now=0, 'ALTER TABLE `TBL_PRIVS` ADD CONSTRAINT `TBL_PRIVS_FK1` FOREIGN KEY (`TBL_ID`) REFERENCES `TBLS` (`TBL_ID`)', 'SELECT 1');
PREPARE _s FROM @_sql;
EXECUTE _s;
DEALLOCATE PREPARE _s;

-- ---- PART_PRIVS (FK: PART_PRIVS_FK1 on PART_ID → PARTITIONS.PART_ID) ----
SET @_col = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
             WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='PART_PRIVS' AND COLUMN_NAME='AUTHORIZER');
SET @_sql = IF(@_col=0, 'ALTER TABLE `PART_PRIVS` ADD `AUTHORIZER` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL', 'SELECT 1');
PREPARE _s FROM @_sql;
EXECUTE _s;
DEALLOCATE PREPARE _s;

SET @_need = (SELECT IF(COUNT(*)=0,1,0) FROM INFORMATION_SCHEMA.STATISTICS
              WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='PART_PRIVS'
                AND INDEX_NAME='PARTPRIVILEGEINDEX' AND COLUMN_NAME='AUTHORIZER' AND SEQ_IN_INDEX=1);
SET @_fk_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE() AND TABLE_NAME='PART_PRIVS' AND CONSTRAINT_NAME='PART_PRIVS_FK1' AND CONSTRAINT_TYPE='FOREIGN KEY');
SET @_sql = IF(@_need=1 AND @_fk_exists=1, 'ALTER TABLE `PART_PRIVS` DROP FOREIGN KEY `PART_PRIVS_FK1`', 'SELECT 1');
PREPARE _s FROM @_sql;
EXECUTE _s;
DEALLOCATE PREPARE _s;
SET @_sql = IF(@_need=1 AND (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='PART_PRIVS' AND INDEX_NAME='PARTPRIVILEGEINDEX')>0, 'ALTER TABLE `PART_PRIVS` DROP INDEX `PARTPRIVILEGEINDEX`', 'SELECT 1');
PREPARE _s FROM @_sql;
EXECUTE _s;
DEALLOCATE PREPARE _s;
SET @_sql = IF(@_need=1, 'ALTER TABLE `PART_PRIVS` ADD INDEX `PARTPRIVILEGEINDEX`(`AUTHORIZER`,`PART_ID`,`PRINCIPAL_NAME`,`PRINCIPAL_TYPE`,`PART_PRIV`,`GRANTOR`,`GRANTOR_TYPE`)', 'SELECT 1');
PREPARE _s FROM @_sql;
EXECUTE _s;
DEALLOCATE PREPARE _s;
SET @_fk_now = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE() AND TABLE_NAME='PART_PRIVS' AND CONSTRAINT_NAME='PART_PRIVS_FK1' AND CONSTRAINT_TYPE='FOREIGN KEY');
SET @_sql = IF(@_need=1 AND @_fk_now=0, 'ALTER TABLE `PART_PRIVS` ADD CONSTRAINT `PART_PRIVS_FK1` FOREIGN KEY (`PART_ID`) REFERENCES `PARTITIONS` (`PART_ID`)', 'SELECT 1');
PREPARE _s FROM @_sql;
EXECUTE _s;
DEALLOCATE PREPARE _s;

-- ---- TBL_COL_PRIVS (FK: TBL_COL_PRIVS_FK1 on TBL_ID → TBLS.TBL_ID) ----
SET @_col = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
             WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='TBL_COL_PRIVS' AND COLUMN_NAME='AUTHORIZER');
SET @_sql = IF(@_col=0, 'ALTER TABLE `TBL_COL_PRIVS` ADD `AUTHORIZER` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL', 'SELECT 1');
PREPARE _s FROM @_sql;
EXECUTE _s;
DEALLOCATE PREPARE _s;

SET @_need = (SELECT IF(COUNT(*)=0,1,0) FROM INFORMATION_SCHEMA.STATISTICS
              WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='TBL_COL_PRIVS'
                AND INDEX_NAME='TABLECOLUMNPRIVILEGEINDEX' AND COLUMN_NAME='AUTHORIZER' AND SEQ_IN_INDEX=1);
SET @_fk_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE() AND TABLE_NAME='TBL_COL_PRIVS' AND CONSTRAINT_NAME='TBL_COL_PRIVS_FK1' AND CONSTRAINT_TYPE='FOREIGN KEY');
SET @_sql = IF(@_need=1 AND @_fk_exists=1, 'ALTER TABLE `TBL_COL_PRIVS` DROP FOREIGN KEY `TBL_COL_PRIVS_FK1`', 'SELECT 1');
PREPARE _s FROM @_sql;
EXECUTE _s;
DEALLOCATE PREPARE _s;
SET @_sql = IF(@_need=1 AND (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='TBL_COL_PRIVS' AND INDEX_NAME='TABLECOLUMNPRIVILEGEINDEX')>0, 'ALTER TABLE `TBL_COL_PRIVS` DROP INDEX `TABLECOLUMNPRIVILEGEINDEX`', 'SELECT 1');
PREPARE _s FROM @_sql;
EXECUTE _s;
DEALLOCATE PREPARE _s;
SET @_sql = IF(@_need=1, 'ALTER TABLE `TBL_COL_PRIVS` ADD INDEX `TABLECOLUMNPRIVILEGEINDEX`(`AUTHORIZER`,`TBL_ID`,`COLUMN_NAME`,`PRINCIPAL_NAME`,`PRINCIPAL_TYPE`,`TBL_COL_PRIV`,`GRANTOR`,`GRANTOR_TYPE`)', 'SELECT 1');
PREPARE _s FROM @_sql;
EXECUTE _s;
DEALLOCATE PREPARE _s;
SET @_fk_now = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE() AND TABLE_NAME='TBL_COL_PRIVS' AND CONSTRAINT_NAME='TBL_COL_PRIVS_FK1' AND CONSTRAINT_TYPE='FOREIGN KEY');
SET @_sql = IF(@_need=1 AND @_fk_now=0, 'ALTER TABLE `TBL_COL_PRIVS` ADD CONSTRAINT `TBL_COL_PRIVS_FK1` FOREIGN KEY (`TBL_ID`) REFERENCES `TBLS` (`TBL_ID`)', 'SELECT 1');
PREPARE _s FROM @_sql;
EXECUTE _s;
DEALLOCATE PREPARE _s;

-- ---- PART_COL_PRIVS (FK: PART_COL_PRIVS_FK1 on PART_ID → PARTITIONS.PART_ID) ----
SET @_col = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
             WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='PART_COL_PRIVS' AND COLUMN_NAME='AUTHORIZER');
SET @_sql = IF(@_col=0, 'ALTER TABLE `PART_COL_PRIVS` ADD `AUTHORIZER` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL', 'SELECT 1');
PREPARE _s FROM @_sql;
EXECUTE _s;
DEALLOCATE PREPARE _s;

SET @_need = (SELECT IF(COUNT(*)=0,1,0) FROM INFORMATION_SCHEMA.STATISTICS
              WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='PART_COL_PRIVS'
                AND INDEX_NAME='PARTITIONCOLUMNPRIVILEGEINDEX' AND COLUMN_NAME='AUTHORIZER' AND SEQ_IN_INDEX=1);
SET @_fk_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE() AND TABLE_NAME='PART_COL_PRIVS' AND CONSTRAINT_NAME='PART_COL_PRIVS_FK1' AND CONSTRAINT_TYPE='FOREIGN KEY');
SET @_sql = IF(@_need=1 AND @_fk_exists=1, 'ALTER TABLE `PART_COL_PRIVS` DROP FOREIGN KEY `PART_COL_PRIVS_FK1`', 'SELECT 1');
PREPARE _s FROM @_sql;
EXECUTE _s;
DEALLOCATE PREPARE _s;
SET @_sql = IF(@_need=1 AND (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='PART_COL_PRIVS' AND INDEX_NAME='PARTITIONCOLUMNPRIVILEGEINDEX')>0, 'ALTER TABLE `PART_COL_PRIVS` DROP INDEX `PARTITIONCOLUMNPRIVILEGEINDEX`', 'SELECT 1');
PREPARE _s FROM @_sql;
EXECUTE _s;
DEALLOCATE PREPARE _s;
SET @_sql = IF(@_need=1, 'ALTER TABLE `PART_COL_PRIVS` ADD INDEX `PARTITIONCOLUMNPRIVILEGEINDEX`(`AUTHORIZER`,`PART_ID`,`COLUMN_NAME`,`PRINCIPAL_NAME`,`PRINCIPAL_TYPE`,`PART_COL_PRIV`,`GRANTOR`,`GRANTOR_TYPE`)', 'SELECT 1');
PREPARE _s FROM @_sql;
EXECUTE _s;
DEALLOCATE PREPARE _s;
SET @_fk_now = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE() AND TABLE_NAME='PART_COL_PRIVS' AND CONSTRAINT_NAME='PART_COL_PRIVS_FK1' AND CONSTRAINT_TYPE='FOREIGN KEY');
SET @_sql = IF(@_need=1 AND @_fk_now=0, 'ALTER TABLE `PART_COL_PRIVS` ADD CONSTRAINT `PART_COL_PRIVS_FK1` FOREIGN KEY (`PART_ID`) REFERENCES `PARTITIONS` (`PART_ID`)', 'SELECT 1');
PREPARE _s FROM @_sql;
EXECUTE _s;
DEALLOCATE PREPARE _s;

-- HIVE-19340: TXN_TYPE
SET @_col = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
             WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='TXNS' AND COLUMN_NAME='TXN_TYPE');
SET @_sql = IF(@_col=0, 'ALTER TABLE TXNS ADD COLUMN TXN_TYPE int DEFAULT NULL', 'SELECT 1');
PREPARE _s FROM @_sql;
EXECUTE _s;
DEALLOCATE PREPARE _s;

-- TAB_COL_STATS index
SET @_idx = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
             WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='TAB_COL_STATS' AND INDEX_NAME='TAB_COL_STATS_IDX');
SET @_sql = IF(@_idx=0, 'CREATE INDEX TAB_COL_STATS_IDX ON TAB_COL_STATS (CAT_NAME, DB_NAME, TABLE_NAME, COLUMN_NAME) USING BTREE', 'SELECT 1');
PREPARE _s FROM @_sql;
EXECUTE _s;
DEALLOCATE PREPARE _s;

-- HIVE-19027: MATERIALIZATION_TIME
SET @_col = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
             WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='MV_CREATION_METADATA' AND COLUMN_NAME='MATERIALIZATION_TIME');
SET @_sql = IF(@_col=0, 'ALTER TABLE `MV_CREATION_METADATA` ADD `MATERIALIZATION_TIME` BIGINT', 'SELECT 1');
PREPARE _s FROM @_sql;
EXECUTE _s;
DEALLOCATE PREPARE _s;
UPDATE `MV_CREATION_METADATA` SET `MATERIALIZATION_TIME` = 0 WHERE `MATERIALIZATION_TIME` IS NULL;
ALTER TABLE `MV_CREATION_METADATA` MODIFY COLUMN `MATERIALIZATION_TIME` BIGINT NOT NULL;

-- CTC_UPDATE_DELETE
SET @_col = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
             WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='COMPLETED_TXN_COMPONENTS' AND COLUMN_NAME='CTC_UPDATE_DELETE');
SET @_sql = IF(@_col=0, 'ALTER TABLE COMPLETED_TXN_COMPONENTS ADD CTC_UPDATE_DELETE char(1)', 'SELECT 1');
PREPARE _s FROM @_sql;
EXECUTE _s;
DEALLOCATE PREPARE _s;
UPDATE COMPLETED_TXN_COMPONENTS SET CTC_UPDATE_DELETE = 'N' WHERE CTC_UPDATE_DELETE IS NULL;
ALTER TABLE COMPLETED_TXN_COMPONENTS MODIFY COLUMN CTC_UPDATE_DELETE char(1) NOT NULL;

-- MATERIALIZATION_REBUILD_LOCKS table
CREATE TABLE IF NOT EXISTS MATERIALIZATION_REBUILD_LOCKS (
  MRL_TXN_ID BIGINT NOT NULL,
  MRL_DB_NAME VARCHAR(128) NOT NULL,
  MRL_TBL_NAME VARCHAR(256) NOT NULL,
  MRL_LAST_HEARTBEAT BIGINT NOT NULL,
  PRIMARY KEY(MRL_TXN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- These lines need to be last.  Insert any changes above.
UPDATE VERSION SET SCHEMA_VERSION='3.1.0', VERSION_COMMENT='Hive release version 3.1.0' where VER_ID=1;
SELECT 'Finished upgrading MetaStore schema from 3.0.0 to 3.1.0' AS MESSAGE;
